eureka:
  instance:
    hostname: config-server
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${REGISTER_SERVER_URL:http://localhost:8761/eureka/}
mybatis:
  mapper-locations: classpath:com/mapper/*Mapper.xml
security:
  basic:
    enabled: false

