spring:
  application:
    name: eureka-server
server:
  port: 1212
#  port: ${PORT:1212}
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    home-page-url: http://localhost:${server.port}/swagger-ui.html
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000


